theme:              jekyll-theme-cayman
title:              Hi I'm Ajay Malekar
email:              ajaymalekar@gmail.com
author:             Start Bootstrap
baseurl:            ""
url:                "https://ajaymalekar.github.io"

# Social Profiles
twitter_username:   linkajay
github_username:    ajaymalekar
facebook_username:  ajaymalekar
instagram_username:  
linkedin_username:  ajaymalekar

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
